Cloud hosted adjustments
OpenLiberty/guide-rest-client-angular pull request #122
Opened 2021-09-28 20:14 UTC by Kevcpro

2021-10-07 22:27 UTC, gkwan-ibm requested changes
@Kevcpro 
- at step4, instead of using launch app, better use curl commands `curl -s http://localhost:9080/artists | jq`
- at step 10, need to tell users where to run `mvn generate-resources`. The static guide need too.
- at the summary step, Nice Work!, the statement is disjointed

2021-10-08 16:09 UTC, gkwan-ibm commented
@Kevcpro 
- at step 10, need to tell users where to run `mvn generate-resources`. The static guide need too.
  - I think should be the `start` directory with backticks instead of root
- at the summary step, Nice Work!, the statement is disjointed
  - is not fixed yet

2021-10-14 20:44 UTC, dmuelle requested changes
a couple minor things, looks good

2021-10-14 20:44 UTC, dmuelle commented on README.adoc
> +type in **9080** to specify the port number for the microservice, and click the **OK** button.
type in-->type

2021-10-14 20:44 UTC, dmuelle commented on README.adoc
> +type in **9080** to specify the port number for the microservice, and click the **OK** button.
type in-->type

2021-10-14 20:44 UTC, dmuelle commented on README.adoc
> +Whenever you change and build your Angular implementation the changes will be reflected automatically
Whenever you change and build your Angular implementation the changes will be reflected automatically...
--->
Whenever you change and build your Angular implementation, the changes are automatically reflected...

2021-10-14 21:16 UTC, dmuelle approved these changes
LGTM thanks

2021-10-15 13:05 UTC, gkwan-ibm commented
addressed https://github.com/OpenLiberty/guides-common/issues/732

2021-10-15 13:38 UTC, gkwan-ibm approved these changes

2021-11-25 21:42 UTC, davidwyao approved these changes

2021-11-30 19:54 UTC, merged